### PR TITLE
Minor correction-there is no "profile.html"--I believe it's been replaced by various students' files.

### PR DESCRIPTION
**Pull request by CodeByLine**
This pull request has been automatically created by learn.co.

### CODE REVIEW

**Comment by AnnJohn** [comment]
hi @CodeByLine there is a profile.html file in there. Thanks.

**Comment by CodeByLine** [comment]
Hi--Can you help me figure out why the "pull request" light still hasn't turned green? (I tried "pull" from every branch there was, hoping to complete the less, but nothing worked :-)

**Comment by AnnJohn** [comment]
hi @CodeByLine this must be a product issue. Using the "Ask a Question" tool in Learn will get you immediate support from our support team. You can also file a bug for this as well- if you hover over your profile pic in Learn, you'll see a menu pop up with an option to "Report a Bug."

Thanks

**Comment by CodeByLine** [comment]
Thanks!

**Comment by CodeByLine** [comment]
FYI--Second time a pull request (via command line) won't turn green, so I went back to the lesson page on Learn, opened Nitrous, and did "learn submit", the light turned green--as did this profile lesson.

**Pull request closed without merging**
